### ISSUE TITLE
Color boxes not showing up anymore in my CSS files.

### ISSUE THREAD

**Issue by RiccardoMPesce** [facelessuser/ColorHelper#79] opened 2016-12-28 15:45 UTC
As stated above, in my ST3 for Ubuntu, the color helper color boxes that are located aside the color value itself, have suddenly disappeared and even after reinstalling they don't show up. I've also removed the plugin color highlighter.

Version: ST3 build 3126
Syntax Highlighter: CSS3
My console outputs are here:

> DPI scale: 1
> startup, version: 3126 linux x64 channel: stable
> executable: /opt/sublime_text/sublime_text
> working dir: /
> packages path: /home/riccardo/.config/sublime-text-3/Packages
> state path: /home/riccardo/.config/sublime-text-3/Local
> zip path: /opt/sublime_text/Packages
> zip path: /home/riccardo/.config/sublime-text-3/Installed Packages
> ignored_packages: ["Makefile", "Vintage"]
> pre session restore time: 0.675007
> warning: mnemonic f not found in menu caption File
> warning: mnemonic t not found in menu caption Tools
> startup time: 0.791182
> first paint time: 0.803734
> first paint time: 0.816525
> reloading plugin Default.auto_indent_tag
> reloading plugin Default.block
> reloading plugin Default.comment
> reloading plugin Default.convert_syntax
> reloading plugin Default.copy_path
> reloading plugin Default.delete_word
> reloading plugin Default.detect_indentation
> reloading plugin Default.duplicate_line
> reloading plugin Default.echo
> reloading plugin Default.exec
> reloading plugin Default.fold
> reloading plugin Default.font
> reloading plugin Default.goto_line
> reloading plugin Default.history_list
> reloading plugin Default.indentation
> reloading plugin Default.install_package_control
> reloading plugin Default.kill_ring
> reloading plugin Default.mark
> reloading plugin Default.new_templates
> reloading plugin Default.open_context_url
> reloading plugin Default.open_in_browser
> reloading plugin Default.pane
> reloading plugin Default.paragraph
> reloading plugin Default.paste_from_history
> reloading plugin Default.profile
> reloading plugin Default.quick_panel
> reloading plugin Default.run_syntax_tests
> reloading plugin Default.save_on_focus_lost
> reloading plugin Default.scroll
> reloading plugin Default.set_unsaved_view_name
> reloading plugin Default.settings
> reloading plugin Default.show_scope_name
> reloading plugin Default.side_bar
> reloading plugin Default.sort
> reloading plugin Default.swap_line
> reloading plugin Default.switch_file
> reloading plugin Default.symbol
> reloading plugin Default.transform
> reloading plugin Default.transpose
> reloading plugin Default.trim_trailing_white_space
> reloading plugin CSS.css_completions
> reloading plugin Diff.diff
> reloading plugin HTML.encode_html_entities
> reloading plugin HTML.html_completions
> reloading plugin 0_package_control_loader.00-package_control
> reloading plugin 0_package_control_loader.01-pygments
> reloading plugin 0_package_control_loader.50-backrefs
> reloading plugin 0_package_control_loader.50-markupsafe
> reloading plugin 0_package_control_loader.50-python-markdown
> reloading plugin 0_package_control_loader.51-python-jinja2
> reloading plugin 0_package_control_loader.55-mdpopups
> reloading plugin AdvancedNewFile.AdvancedNewFile
> reloading plugin Alignment.Alignment
> reloading plugin All Autocomplete.all_views_completions
> reloading plugin AngularJS.AngularJS-sublime-package
> reloading plugin AngularJS.jscompletions
> reloading plugin AngularJS.message
> reloading plugin AngularJS.sublime_commands
> reloading plugin AngularJS.viewlocation
> reloading plugin Auto Semi-Colon.AutoSemiColon
> reloading plugin Boxy Theme.BT
> reloading plugin BracketHighlighter.bh_core
> reloading plugin BracketHighlighter.bh_logging
> reloading plugin BracketHighlighter.bh_plugin
> reloading plugin BracketHighlighter.bh_popup
> reloading plugin BracketHighlighter.bh_regions
> reloading plugin BracketHighlighter.bh_remove
> reloading plugin BracketHighlighter.bh_rules
> reloading plugin BracketHighlighter.bh_search
> reloading plugin BracketHighlighter.bh_swapping
> reloading plugin BracketHighlighter.bh_wrapping
> reloading plugin BracketHighlighter.support
> reloading plugin Browser Integration.browser
> reloading plugin Browser Integration.browser_integration
> Browser Integration :: Intializing Browser instance.
> reloading plugin Browser Integration.browser_integration_autoreload
> reloading plugin Browser Integration.browser_integration_class
> reloading plugin Browser Integration.browser_integration_click
> reloading plugin Browser Integration.browser_integration_execute
> reloading plugin Browser Integration.browser_integration_inject
> reloading plugin Browser Integration.browser_integration_install
> reloading pluginDownloading `chromedriver` executable 
>   from 'http://sublime.apiad.net/browser-integration/chromedriver/chromedriver-linux-64'
>   into '/home/riccardo/.config/sublime-text-3/Installed Packages/chromedriver'
> Browser Integration.browser_integration_launch[Start] Browser Integration :: Downloading chromedriver executable.
> 
> reloading plugin Browser Integration.browser_integration_live_localstorage
> reloading plugin Browser Integration.browser_integration_livecss
> reloading plugin Browser Integration.browser_integration_localstorage
> reloading plugin Browser Integration.browser_integration_main_menu
> reloading plugin Browser Integration.browser_integration_navigate
> reloading plugin Browser Integration.browser_integration_play
> reloading plugin Browser Integration.browser_integration_quit
> reloading plugin Browser Integration.browser_integration_record
> reloading plugin Browser Integration.browser_integration_reload
> reloading plugin Browser Integration.browser_integration_select
> reloading plugin Browser Integration.browser_integration_selectint
> reloading plugin Browser Integration.browser_integration_source
> reloading plugin Browser Integration.browser_integration_stop
> reloading plugin Browser Integration.browser_integration_stylesheets
> reloading plugin Browser Integration.browser_integration_type
> reloading plugin Browser Refresh.BrowserRefresh
> reloading plugin C++NamespaceTool.C++NamespaceTool
> reloading plugin CMakeEditor.CMakeEditor
> reloading plugin CSS3.css3_completions
> reloading pluginException in thread Thread-1:
> Traceback (most recent call last):
>   File "./python3.3/urllib/request.py", line 1248, in do_open
>   File "./python3.3/http/client.py", line 1065, in request
>   File "./python3.3/http/client.py", line 1103, in _send_request
>   File "./python3.3/http/client.py", line 1061, in endheaders
>   File "./python3.3/http/client.py", line 906, in _send_output
>   File "./python3.3/http/client.py", line 844, in send
>   File "./python3.3/http/client.py", line 822, in connect
>   File "./python3.3/socket.py", line 417, in create_connection
> socket.gaierror: [Errno -2] Name or service not known
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "./python3.3/threading.py", line 901, in _bootstrap_inner
>   File "./python3.3/threading.py", line 858, in run
>   File "browser_integration_install in /home/riccardo/.config/sublime-text-3/Installed Packages/Browser Integration.sublime-package", line 34, in install_chromedriver
>   File "./python3.3/urllib/request.py", line 156, in urlopen
>   File "./python3.3/urllib/request.py", line 469, in open
>   File "./python3.3/urllib/request.py", line 487, in _open
>   File "./python3.3/urllib/request.py", line 447, in _call_chain
>   File "./python3.3/urllib/request.py", line 1274, in http_open
>   File "./python3.3/urllib/request.py", line 1251, in do_open
> urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
> 
>  CSS3.rgb_to_hex
> reloading plugin CSSLint.CSSLint
> reloading plugin CSSLint.version_file_checker
> reloading plugin Can I Use.useIt
> reloading plugin Clang Format.clang_format
> reloading plugin ColorHelper.color_helper
> [End] Browser Integration :: Downloading chromedriver executable.
> reloading plugin ColorHelper.color_helper_insert
> reloading plugin ColorHelper.color_helper_picker
> reloading plugin ColorHelper.color_helper_util
> reloading plugin ColorHelper.multiconf
> reloading plugin ColorHelper.support
> reloading plugin CppBuilder.Builder
> reloading plugin CppBuilder.CppBuilder
> reloading plugin CppBuilder.MakeProject
> reloading plugin CppBuilder.MakerClass
> reloading plugin CppBuilder.ProjectHandler
> reloading plugin CppBuilder.edit
> reloading plugin Django Manage Commands.django-commands
> reloading plugin DocBlockr.jsdocs
> reloading plugin Emmet.emmet-plugin
> reloading plugin FileDiffs.file_diffs
> reloading plugin Git.git_commands
> reloading plugin GitGutter.git_gutter
> reloading plugin GitGutter.git_gutter_compare
> reloading plugin GitGutter.git_gutter_events
> reloading plugin GitGutter.git_gutter_handler
> reloading plugin GitGutter.git_gutter_jump_to_changes
> reloading plugin GitGutter.git_gutter_popup
> reloading plugin GitGutter.git_gutter_settings
> reloading plugin GitGutter.git_gutter_show_diff
> reloading plugin GitGutter.git_helper
> reloading plugin GitGutter.promise
> reloading plugin Github Tools.github
> reloading plugin Github Tools.github_blame
> reloading plugin Github Tools.github_copy_link
> reloading plugin Github Tools.github_create_pr
> reloading plugin Github Tools.github_file_history
> reloading plugin Github Tools.github_issues
> reloading plugin Github Tools.github_open
> reloading plugin Github Tools.github_plugin_settings
> reloading plugin Github Tools.github_pulls
> reloading plugin Github Tools.github_repository
> reloading plugin HTML5.encode_html_entities
> reloading plugin HTML5.html_completions
> reloading plugin HTMLBeautify.HTMLBeautify
> reloading plugin Javatar.Javatar
> reloading plugin JsDebuggr.breakpoint
> reloading plugin JsDebuggr.jsdebuggr
> reloading plugin JsDebuggr.utils
> reloading plugin JsFormat.js_formatter
> reloading plugin Makefile Improved.Makefile Improved
> reloading plugin Material Theme.MT
> reloading plugin Nodejs.Nodejs
> reloading plugin Nodejs.__init__
> reloading plugin Package Control.1_reloader
> reloading plugin Package Control.2_bootstrap
> reloading plugin Package Control.Package Control
> reloading plugin Package Syncing.Package Syncing
> reloading plugin SideBarEnhancements.SideBar
> reloading plugin SideBarEnhancements.SideBarAPI
> reloading plugin SideBarEnhancements.SideBarDefaultDisable
> reloading plugin SideBarEnhancements.Stats
> reloading plugin Skins.skins
> reloading plugin SublimeLinter-contrib-cmakelint.linter
> SublimeLinter: cmakelint linter loaded 
> reloading plugin SublimeLinter-contrib-htmlhint.linter
> SublimeLinter: htmlhint linter loaded 
> reloading plugin SublimeLinter-csslint.linter
> SublimeLinter: csslint linter loaded 
> reloading plugin SublimeLinter-gjslint.linter
> SublimeLinter: gjslint linter loaded 
> reloading plugin SublimeLinter-jshint.linter
> SublimeLinter: jshint linter loaded 
> reloading plugin SublimeLinter-jsl.linter
> SublimeLinter: jsl linter loaded 
> reloading plugin SublimeLinter-json.linter
> SublimeLinter: json linter loaded 
> reloading plugin SublimeLinter-jsxhint.linter
> SublimeLinter: jsxhint linter loaded 
> reloading plugin jQuery Mobile Demos.JqueryMobileDemos
> reloading plugin jQueryDocs.jQueryDocs
> reloading plugin pastebin-sublime-plugin.pastebin
> reloading plugin Anaconda.anaconda
> reloading plugin Anaconda.setup
> reloading plugin Anaconda.version
> reloading plugin Babel.Babel
> reloading plugin CSScomb.CSScomb
> reloading plugin ColorPicker.sublimecp
> reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
> reloading plugin JSHint.JSHint
> reloading plugin JavaScript Completions._generated_2016_09_26_at_21_37_12
> reloading plugin JavaScript Completions.reloader
> reloading plugin LiveReload.CoffeescriptPlugin
> reloading plugin LiveReload.CommandAPI
> reloading plugin LiveReload.CompassPlugin
> reloading plugin LiveReload.LESSPlugin
> reloading plugin LiveReload.LiveReload
> reloading plugin LiveReload.SimpleReloadCallback
> reloading plugin LiveReload.SimpleReloadPlugin
> reloading plugin LiveReload.SimpleReloadPluginDelay
> reloading plugin LiveReload.SimpleWSCallback
> reloading plugin LiveReload.__init__
> reloading plugin Ruby Debugger.debug_command
> reloading plugin Ruby Debugger.toggle_breakpoint_command
> reloading plugin Ruby Debugger.view_helper_command
> reloading plugin SublimeCodeIntel.SublimeCodeIntel
> reloading plugin SublimeCodeIntel.ordereddict
> reloading plugin SublimeLinter.commands
> reloading plugin SublimeLinter.sublimelinter
> reloading plugin SublimeREPL.__init__
> reloading plugin SublimeREPL.completions
> reloading plugin SublimeREPL.lang_integration
> reloading plugin SublimeREPL.run_existing_command
> reloading plugin SublimeREPL.sublimerepl
> reloading plugin SublimeREPL.sublimerepl_build_system_hack
> reloading plugin SublimeREPL.text_transfer
> plugins loaded
> CSSLint is a .sublime-package; Verifying required files.
> user_preferences_file: /home/riccardo/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
> s: {
> 	"always_show_minimap_viewport": true,
> 	"auto_complete": true,
> 	"auto_complete_selector": true,
> 	"bold_folder_labels": true,
> 	"caret_extra_bottom": 2,
> 	"caret_extra_top": 2,
> 	"caret_extra_width": 2,
> 	"caret_style": "phase",
> 	"color_scheme": "Packages/User/SublimeLinter/Material Spacegray (SL).tmTheme",
> 	"drag_text": false,
> 	"font_face": "Inconsolata-g",
> 	"font_options":
> 	[
> 		"directwrite",
> 		"no_italic"
> 	],
> 	"font_size": "10.5",
> 	"ignored_packages":
> 	[
> 		"Makefile",
> 		"Vintage"
> 	],
> 	"line_padding_bottom": 1,
> 	"line_padding_top": 1,
> 	"material_theme_accent_cyan": true,
> 	"material_theme_compact_sidebar": true,
> 	"material_theme_tree_headings": true,
> 	"overlay_scroll_bars": "enabled",
> 	"theme": "Material Spacegray.sublime-theme"
> }
> 
> SublimeLinter: debug mode: off 
> SublimeLinter: WARNING: csslint deactivated, cannot locate 'csslint' 
>  - Django: ChangeDefaultCommand ready
>  - Django: DjangoAppCommand ready
>  - Django: DjangoCheckCommand ready
>  - Django: DjangoCommand ready
>  - Django: DjangoCustomCommand ready
>  - Django: DjangoDbShellCommand ready
>  - Django: DjangoHelpCommand ready
>  - Django: DjangoInitialSchemaMigrationCommand ready
>  - Django: DjangoListMigrationsCommand ready
>  - Django: DjangoMakeMigrationCommand ready
>  - Django: DjangoMigrateAppCommand ready
>  - Django: DjangoMigrateCommand ready
>  - Django: DjangoNewAppCommand ready
>  - Django: DjangoNewProjectCommand ready
>  - Django: DjangoOpenDocsCommand ready
>  - Django: DjangoOtherCommand ready
>  - Django: DjangoRunCommand ready
>  - Django: DjangoRunCustomCommand ready
>  - Django: DjangoSchemaMigrationCommand ready
>  - Django: DjangoSearchDocsCommand ready
>  - Django: DjangoShellCommand ready
>  - Django: DjangoSimpleCommand ready
>  - Django: DjangoSqlMigrationCommand ready
>  - Django: DjangoSyncdbCommand ready
>  - Django: DjangoTestAllCommand ready
>  - Django: DjangoTestAppCommand ready
>  - Django: PipFreezeCommand ready
>  - Django: PipFreezeToFileCommand ready
>  - Django: PipInstallPackagesCommand ready
>  - Django: PipInstallRequirementsCommand ready
>  - Django: SetProjectInterpreterCommand ready
>  - Django: SetVirtualEnvCommand ready
>  - Django: TerminalHereCommand ready
>  - Django: VirtualEnvCommand ready
> LiveReload: added file /livereload.js with content-type: text/javascript
> INFO:WebSocketClient:Starting server
>  - Django: ChangeDefaultCommand ready
>  - Django: DjangoAppCommand ready
>  - Django: DjangoCheckCommand ready
>  - Django: DjangoCommand ready
>  - Django: DjangoCustomCommand ready
>  - Django: DjangoDbShellCommand ready
>  - Django: DjangoHelpCommand ready
>  - Django: DjangoInitialSchemaMigrationCommand ready
>  - Django: DjangoListMigrationsCommand ready
>  - Django: DjangoMakeMigrationCommand ready
>  - Django: DjangoMigrateAppCommand ready
>  - Django: DjangoMigrateCommand ready
>  - Django: DjangoNewAppCommand ready
>  - Django: DjangoNewProjectCommand ready
>  - Django: DjangoOpenDocsCommand ready
>  - Django: DjangoOtherCommand ready
>  - Django: DjangoRunCommand ready
>  - Django: DjangoRunCustomCommand ready
>  - Django: DjangoSchemaMigrationCommand ready
>  - Django: DjangoSearchDocsCommand ready
>  - Django: DjangoShellCommand ready
>  - Django: DjangoSimpleCommand ready
>  - Django: DjangoSqlMigrationCommand ready
>  - Django: DjangoSyncdbCommand ready
>  - Django: DjangoTestAllCommand ready
>  - Django: DjangoTestAppCommand ready
>  - Django: PipFreezeCommand ready
>  - Django: PipFreezeToFileCommand ready
>  - Django: PipInstallPackagesCommand ready
>  - Django: PipInstallRequirementsCommand ready
>  - Django: SetProjectInterpreterCommand ready
>  - Django: SetVirtualEnvCommand ready
>  - Django: TerminalHereCommand ready
>  - Django: VirtualEnvCommand ready
> Skins: loading Packages/User/Saved Skins.skins failed with resource not found
> Traceback (most recent call last):
>   File "/opt/sublime_text/sublime_plugin.py", line 701, in is_enabled_
>     ret = self.is_enabled()
>   File "django-commands in /home/riccardo/.config/sublime-text-3/Installed Packages/Django Manage Commands.sublime-package", line 320, in is_enabled
>   File "django-commands in /home/riccardo/.config/sublime-text-3/Installed Packages/Django Manage Commands.sublime-package", line 69, in get_version
>   File "./python3.3/subprocess.py", line 589, in check_output
> subprocess.CalledProcessError: Command '['/usr/bin/python3', '-c', 'import django;print(django.get_version())']' returned non-zero exit status 1
> WINDOW COMMAND ENABLED True
> WINDOW COMMAND ENABLED True
> WARNING:process:Could not import subprocess32 module, falling back to subprocess module
> WINDOW COMMAND ENABLED True
> WINDOW COMMAND ENABLED True
> WINDOW COMMAND ENABLED True
> WINDOW COMMAND ENABLED False
> Emmet: No need to update PyV8
> reloading settings Packages/User/Javatar.sublime-settings
> reloading settings Packages/User/Package Syncing.sublime-settings
> warning: mnemonic f not found in menu caption File
> warning: mnemonic t not found in menu caption Tools
> Javatar snippet Class.javatar loaded
> Javatar snippet Enumerator.javatar loaded
> Javatar snippet Interface.javatar loaded
> warning: mnemonic f not found in menu caption File
> warning: mnemonic t not found in menu caption Tools
> Package Syncing: Start Complete Sync
> Package Syncing: Already running
> Package Syncing: Updated /home/riccardo/st3-backup/Javatar.sublime-settings
> Package Syncing: End Complete Sync
> Javatar package "Java Standard Edition 8" loaded with 4385 classes in 213 packages
> [Javatar] Use default Java version [JDK1.8.0u111]
> reloading settings Packages/User/Javatar.sublime-settings
> warning: mnemonic f not found in menu caption File
> warning: mnemonic t not found in menu caption Tools
> Package Syncing: Updated /home/riccardo/st3-backup/Javatar.sublime-settings
> Package Control: Skipping automatic upgrade, last run at 2016-12-28 16:08:28, next run at 2016-12-28 17:08:28 or after
> Skins: loading Packages/User/Saved Skins.skins failed with resource not found
> Traceback (most recent call last):
>   File "/opt/sublime_text/sublime_plugin.py", line 701, in is_enabled_
>     ret = self.is_enabled()
>   File "django-commands in /home/riccardo/.config/sublime-text-3/Installed Packages/Django Manage Commands.sublime-package", line 320, in is_enabled
>   File "django-commands in /home/riccardo/.config/sublime-text-3/Installed Packages/Django Manage Commands.sublime-package", line 69, in get_version
>   File "./python3.3/subprocess.py", line 589, in check_output
> subprocess.CalledProcessError: Command '['/usr/bin/python3', '-c', 'import django;print(django.get_version())']' returned non-zero exit status 1
> WINDOW COMMAND ENABLED True
> WINDOW COMMAND ENABLED True
> WINDOW COMMAND ENABLED True
> WINDOW COMMAND ENABLED True
> WINDOW COMMAND ENABLED True
> WINDOW COMMAND ENABLED False
> SublimeLinter: WARNING: jsl deactivated, cannot locate 'jsl' 
> SublimeLinter: WARNING: gjslint deactivated, cannot locate 'gjslint' 
> SublimeLinter: WARNING: jshint deactivated, cannot locate 'jshint' 
> Traceback (most recent call last):
>   File "/opt/sublime_text/sublime_plugin.py", line 389, in run_callback
>     expr()
>   File "/opt/sublime_text/sublime_plugin.py", line 522, in <lambda>
>     run_callback('on_activated', callback, lambda: callback.on_activated(v))
>   File "/home/riccardo/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 278, in on_activated
>     self.check_syntax(view)
>   File "/home/riccardo/.config/sublime-text-3/Packages/SublimeLinter/sublimelinter.py", line 205, in check_syntax
>     Linter.assign(view, reset=True)
>   File "/home/riccardo/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 734, in assign
>     if not linter_class.disabled and linter_class.can_lint(syntax):
>   File "./python3.3/functools.py", line 251, in wrapper
>   File "/home/riccardo/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 1602, in can_lint
>     status = 'WARNING: {} deactivated, cannot locate \'{}\''.format(cls.name, executable)
> UnboundLocalError: local variable 'executable' referenced before assignment
> reloading settings Packages/User/Javatar.sublime-settings
> warning: mnemonic f not found in menu caption File
> warning: mnemonic t not found in menu caption Tools
> Package Syncing: Updated /home/riccardo/st3-backup/Javatar.sublime-settings
> Traceback (most recent call last):
>   File "/opt/sublime_text/sublime_plugin.py", line 389, in run_callback
>     expr()
>   File "/opt/sublime_text/sublime_plugin.py", line 428, in <lambda>
>     run_callback('on_load', callback, lambda: callback.on_load(v))
>   File "jsdebuggr in /home/riccardo/.config/sublime-text-3/Installed Packages/JsDebuggr.sublime-package", line 210, in on_load
>   File "utils in /home/riccardo/.config/sublime-text-3/Installed Packages/JsDebuggr.sublime-package", line 26, in get_current_syntax
> TypeError: 'NoneType' object is not iterable
> Traceback (most recent call last):
>   File "/opt/sublime_text/sublime_plugin.py", line 389, in run_callback
>     expr()
>   File "/opt/sublime_text/sublime_plugin.py", line 428, in <lambda>
>     run_callback('on_load', callback, lambda: callback.on_load(v))
>   File "jsdebuggr in /home/riccardo/.config/sublime-text-3/Installed Packages/JsDebuggr.sublime-package", line 210, in on_load
>   File "utils in /home/riccardo/.config/sublime-text-3/Installed Packages/JsDebuggr.sublime-package", line 26, in get_current_syntax
> TypeError: 'NoneType' object is not iterable
> reloading settings Packages/User/Javatar.sublime-settings
> warning: mnemonic f not found in menu caption File
> warning: mnemonic t not found in menu caption Tools
> Package Syncing: Updated /home/riccardo/st3-backup/Javatar.sublime-settings
> reloading settings Packages/User/Javatar.sublime-settings
> warning: mnemonic f not found in menu caption File
> warning: mnemonic t not found in menu caption Tools
> Package Syncing: Updated /home/riccardo/st3-backup/Javatar.sublime-settings
> reloading settings Packages/User/Javatar.sublime-settings
> warning: mnemonic f not found in menu caption File
> warning: mnemonic t not found in menu caption Tools
> Package Syncing: Updated /home/riccardo/st3-backup/Javatar.sublime-settings
> reloading settings Packages/User/Javatar.sublime-settings
> warning: mnemonic f not found in menu caption File
> warning: mnemonic t not found in menu caption Tools
> Package Syncing: Updated /home/riccardo/st3-backup/Javatar.sublime-settings
> reloading settings Packages/User/Javatar.sublime-settings
> warning: mnemonic f not found in menu caption File
> warning: mnemonic t not found in menu caption Tools
> Package Syncing: Updated /home/riccardo/st3-backup/Javatar.sublime-settings
> reloading settings Packages/User/Javatar.sublime-settings
> warning: mnemonic f not found in menu caption File
> warning: mnemonic t not found in menu caption Tools
> Package Syncing: Updated /home/riccardo/st3-backup/Javatar.sublime-settings
> reloading settings Packages/User/Javatar.sublime-settings
> warning: mnemonic f not found in menu caption File
> warning: mnemonic t not found in menu caption Tools
> Package Syncing: Updated /home/riccardo/st3-backup/Javatar.sublime-settings

Here are my packages:

> 0_package_control_loader.sublime-package
> 1337 Color Scheme.sublime-package
> 1self.sublime-settings
> 4GL.sublime-package
> AdvancedNewFile.sublime-package
> Alignment.sublime-package
> All Autocomplete.sublime-package
> AngularJS.sublime-package
> Auto Semi-Colon.sublime-package
> Boxy Theme.sublime-package
> BracketHighlighter.sublime-package
> Browser Integration.sublime-package
> Browser Refresh.sublime-package
> C++11.sublime-package
> C11.sublime-package
> C99.sublime-package
> Can I Use.sublime-package
> C++ Completions.sublime-package
> Clang Format.sublime-package
> CMakeEditor.sublime-package
> CMakeSnippets.sublime-package
> CMake.sublime-package
> C++NamespaceTool.sublime-package
> ColorHelper.sublime-package
> CppBuilder.sublime-package
> C++ Snippets.sublime-package
> CSS3.sublime-package
> CSSLint.sublime-package
> C++ Starting Kit.sublime-package
> C.sublime-settings
> CUDA C++.sublime-package
> Default (Linux).sublime-keymap
> Default.sublime-theme
> Django Manage Commands.sublime-package
> DocBlockr.sublime-package
> Emmet.sublime-package
> Emmet.sublime-settings
> FileDiffs.sublime-package
> GitGutter.sublime-package
> Github Tools.sublime-package
> Git.sublime-package
> HTML5.sublime-package
> HTMLBeautify.sublime-package
> HTMLEntity Snippets.sublime-package
> HTML Extended.sublime-package
> HTML Head Snippets.sublime-package
> HTML Snippets.sublime-package
> HTML.sublime-settings
> Java Bytecode.sublime-package
> JavaScript Console.sublime-package
> JavaScript & NodeJS Snippets.sublime-package
> JavaScript.sublime-settings
> Javatar.sublime-package
> jQueryDocs.sublime-package
> jQuery Mobile Demos.sublime-package
> jQuery Snippets pack.sublime-package
> jQuery.sublime-package
> JsDebuggr.sublime-package
> JsFormat.sublime-package
> Makefile Improved.sublime-package
> Makefile Plus.sublime-package
> MarkdownHighlighting.sublime-package
> Materialize.sublime-package
> Material Theme.sublime-package
> Nodejs.sublime-package
> Numix Theme.sublime-package
> One Dark Color Scheme.sublime-package
> One Dark Material - Theme.sublime-package
> Package Control.sublime-package
> Package Control.sublime-settings
> Package Syncing.sublime-package
> pack.txt
> pastebin-sublime-plugin.sublime-package
> Plain text.sublime-settings
> Preferences.sublime-settings
> PyV8
> Qt Completions for C++.sublime-package
> React Development Snippets.sublime-package
> React ES6 Snippets.sublime-package
> ReactJS.sublime-package
> Ruby Completions.sublime-package
> SideBarEnhancements.sublime-package
> Skins.sublime-package
> SublimeLinter-contrib-cmakelint.sublime-package
> SublimeLinter-contrib-htmlhint.sublime-package
> SublimeLinter-csslint.sublime-package
> SublimeLinter-gjslint.sublime-package
> SublimeLinter-jshint.sublime-package
> SublimeLinter-jsl.sublime-package
> SublimeLinter-json.sublime-package
> SublimeLinter-jsxhint.sublime-package
> Theme - Brogrammer.sublime-package
> Theme - itg.flat.sublime-package
> Theme - Numix.sublime-package
> Theme - Spacegray.sublime-package

Edit. I added the missing details
Edit 2. Solved it by setting the syntax to css (not css3)

**Comment by facelessuser** [comment] 2016-12-28 16:33
1. Please follow the issue template to get support. While I really do appreciate the error log which is very helpful, there are also a number of other things I request in the template like package version numbers and what syntax highlighter does the issue occur under etc.  Currently, I am marking this issue invalid until updated.  But...
2. if this is related to no previews in the CSS3 package, then this is a duplicate of #73, and this issue can be closed anyways as I am already aware of this and just haven't gotten around to updated CSS3 support.
3. It looks like you have some unrelated issues with something in your setup you should look into:

```
reloading pluginException in thread Thread-1:
Traceback (most recent call last):
File "./python3.3/urllib/request.py", line 1248, in do_open
File "./python3.3/http/client.py", line 1065, in request
File "./python3.3/http/client.py", line 1103, in _send_request
File "./python3.3/http/client.py", line 1061, in endheaders
File "./python3.3/http/client.py", line 906, in _send_output
File "./python3.3/http/client.py", line 844, in send
File "./python3.3/http/client.py", line 822, in connect
File "./python3.3/socket.py", line 417, in create_connection
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred, but this has nothing to do with ColorHelper:

Traceback (most recent call last):
File "./python3.3/threading.py", line 901, in _bootstrap_inner
File "./python3.3/threading.py", line 858, in run
File "browser_integration_install in /home/riccardo/.config/sublime-text-3/Installed Packages/Browser Integration.sublime-package", line 34, in install_chromedriver
File "./python3.3/urllib/request.py", line 156, in urlopen
File "./python3.3/urllib/request.py", line 469, in open
File "./python3.3/urllib/request.py", line 487, in _open
File "./python3.3/urllib/request.py", line 447, in _call_chain
File "./python3.3/urllib/request.py", line 1274, in http_open
File "./python3.3/urllib/request.py", line 1251, in do_open
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
```

**Comment by facelessuser** [comment] 2016-12-29 17:57
I'm rolling out a fix for CSS3 today, and since you haven't responded with info as to what syntax previews aren't showing up in, I am assuming CSS3 and closing this.

**Closed** 2016-12-29 17:58 UTC
Labels: Invalid
