### ISSUE TITLE
They keep adding up :o

### ISSUE THREAD

**Issue by katerlouis** [facelessuser/ColorHelper#66] opened 2016-10-19 21:33 UTC
This comes from a php file (97% html in there..)

<img width="737" alt="e715f225-f066-440b-923d-af44ec04e4f8" src="https://cloud.githubusercontent.com/assets/1983382/19538374/0518eb74-9654-11e6-946e-3f8d9ca35532.png">

They just keep adding up. I guess it's everytime I re-open my MacBook :D

But in my less and css files still no colors :'(

```
- ST ver.:        3126
- Platform:       osx
- Arch:           x64
- Plugin ver.:    2.1.1
- Install via PC: True
- mdpopups ver.:  1.10.0
- markdown ver.:  2.6.6
- pygments ver.:  2.1a0
- jinja2 ver.:    2.8
```

**Comment by facelessuser** [comment] 2016-10-19 23:08
This is a duplicate of #57.  As for less, it is quite possible support needs to be added int the settings file.  I simply haven't had the time to look at #57 yet.

**Comment by katerlouis** [comment] 2016-10-20 22:20
Sorry for **double**post then.
Searched but didn't think of the term `double` here ;)
I'm cursed! I need this plugin more than food (at least it feels that way..) and it just won't work for me :'(

**Comment by facelessuser** [comment] 2016-10-20 22:22
Won't work in less?  Or doesn't work because of the duplication of previews.

If we are talking about less, just look at the settings, and add support for less.  If we're talking about the duplication issue, I just need time to look at it.

**Comment by katerlouis** [comment] 2016-10-20 22:32
The rectangles won't show in LESS files, yeah.
I looked at the settings and am too confused to know even where to start. :X  
Couldn't find an issue or an explanation in the readme– could you just tell me here real quick? :X

**Comment by facelessuser** [comment] 2016-10-20 22:40
It's talked about here (but only briefly): http://facelessuser.github.io/ColorHelper/usage/#color_scanning.

Basically you want to copy something like CSS:

```
{
            "syntax_files": [],
            "syntax_filter": "whitelist",
            "base_scopes": [
                "source.css",
                "text.html"
            ],
            "scan_scopes": [
                // https://packagecontrol.io/packages/CSS3
                "meta.property-list.css -support.type.property-name.css -comment -string",
                // CSS, CSS in HTML etc. (based on: Sublime Default)
                "meta.property-value.css -comment -string",
                // CSS3, CSS3 in HTML etc. (based on: https://packagecontrol.io/packages/CSS3)
                "meta.value.css -comment -string",
                // HTML attributes (based on: Sublime Default)
                "meta.tag.inline.any.html string.quoted",
                "meta.tag.any.html meta.attribute-with-value.style.html"
            ],
            "scan_completion_scopes": [],
            "extensions": [],
            "allowed_colors": ["css3"],
            "use_hex_argb": false,
            "compress_hex_output": true
        },
```

And pay attention to to areas: `base_scopes` and `scan_scopes`.

Base scopes are going to usually be the source scope.  This is used to to tell if the feature should be enabled in this file.  I don't know what syntax you are using, but maybe it is something like `source.less` -- I don't actually know though.

Next you want to populate scan scopes with the scopes that usually contain the colors.  You want to limit it as much as possible to prevent from scanning the entire file.

**Comment by katerlouis** [comment] 2016-10-20 22:51
I am really confused :X – Why isn't LESS supported by colorhelper by default?!

**Comment by facelessuser** [comment] 2016-10-20 22:53
Because I don't use LESS.

**Comment by facelessuser** [comment] 2016-10-20 22:53
I'm not against LESS being in by default, but nobody has added support for it.

**Comment by katerlouis** [comment] 2016-10-20 22:54
Could you? Or at least tell me what to write in the user.settings now? ^^

**Comment by facelessuser** [comment] 2016-10-20 23:16
If I were to do it, I would use the ScopeHunter plugin to analyze what the base scope and the scopes of interest are.  At the very minimum I would use the base scope minus comments and strings.  It will probably scan unnecessary stuff, but it is better than nothing.  I would probably follow that strategy.  If you are looking for a quick fix, you probably aren't going to get it.  Someone has to put in the time; either you, me, or someone else.  I've outlined above an approach you can take if you are motivated.

I don't use LESS, so I have to download less syntax, familiarize myself with less (probably not too much), figure out which scopes to target, test it out, etc.  You can see why it makes more sense for you to do it.  You use LESS, you have an interest in LESS support, you will be much more motivated to spend personal time to get LESS support in than I am.  If I never added LESS support, it would probably never affect my usage of the plugin.

You could argue, "but you could do it faster".  Yes, but this is low priority for me.  The first thing I'm going to spend my time on (when I have some to spend on this) is the duplication bug.  Allocation of my time is best directed to high priority issues like the duplication bug.  I hope you understand, that is why I created the settings file, so **others** can add stuff like this so I don't have to.  There are plenty of examples to help you.

I am confident that you can figure it out, and I am willing to answer questions if you get confused.

**Comment by katerlouis** [comment] 2016-10-21 09:26
I'm on to it, Boss 8)

**Comment by facelessuser** [comment] 2016-10-31 14:40
I'm going to close this as this is a duplicate for #57.  I will try and update its title to hopefully be more descriptive.  I am hoping to start looking at that issue soon.

**Closed** 2016-10-31 14:40 UTC
