### ISSUE TITLE
Color picker is much too small, doesn't change size when set to large

### ISSUE THREAD

**Issue by GameKyuubi** [facelessuser/ColorHelper#86] opened 2017-03-02 11:08 UTC
## Description

Color picker is so small it is basically unusable

![image](https://cloud.githubusercontent.com/assets/6174313/23504576/7fd658fe-ff83-11e6-90da-6983dc34015b.png)

## Support Info

(support info didn't actually get copied to clipboard, had to write by hand)
- ST ver.: 3126
- Platform: windows
- Arch: x64
- Plugin ver.: 2.4.2
- Install via PC: True
- mdpopups ver.: 1.13.1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

1) install color helper via package manager
2) type a color field
3) click on color picker

**Comment by facelessuser** [comment] 2017-04-10 01:00
You will have to post your settings.  Right now I don't have enough information to go on.  When I change the size for my system in the settings file, the color boxes get larger or smaller as expected.

**Comment by GameKyuubi** [comment] 2017-04-11 11:53
The settings are default.  Here is my settings file:

` `

**Comment by facelessuser** [comment] 2017-04-12 02:57
Did you check out the documentation?  It mentions their is a setting to control graphic sizes: http://facelessuser.github.io/ColorHelper/usage/#graphic_size.

**Comment by GameKyuubi** [comment] 2017-04-12 03:07
Yes, it changes nothing.  Setting to "large" does nothing, or the difference is so imperceptible it might as well be nothing.

**Comment by GameKyuubi** [comment] 2017-04-12 03:26
Ah, I believe I've found the issue.  The picker palette size is related to the font in use (but *not* the font size).

**Comment by facelessuser** [comment] 2017-04-12 03:28
Are you setting it proper? Can you post the settings content and let me know what that settings file is named? These questions may seem silly, but this is working fine on my 4k monitor on all my systems.  I have to confirm the obvious is in fact setup proper.

**Comment by GameKyuubi** [comment] 2017-04-12 03:29
If I set the font to 'Courier' it is significantly more usable, but "large" still does nothing.  The font I'm using is MonteCarlo Fixed 12, from https://www.bok.net/MonteCarlo/

**Comment by GameKyuubi** [comment] 2017-04-12 03:29
My settings:

`{
  "graphic_size": "large",
  "inline_preview_offset": 12,
}`

**Comment by facelessuser** [comment] 2017-04-12 03:31
I'll play with don't sizes over here as well.  I suspect something isn't quite right on your system. It is also odd that the support info didn't copy to your clipboard either.

**Comment by facelessuser** [comment] 2017-04-12 03:32
Disregard my comment, I didn't see your recent posts.

**Comment by GameKyuubi** [comment] 2017-04-12 03:40
Ah I see why adjusting font size did nothing.  Changing the font size with the picker open doesn't work, I have to change the font size and then reopen the picker to see the changes.  MonteCarlo is a particularly compact programming font so it might be good to include an integer-based option for scaling the size of the picker.  Also did you notice that the font size used in the helper window is smaller than the current set size?  Is that intentional?

**Comment by facelessuser** [comment] 2017-04-12 04:00
Image sizes are not based on font size, at least not directly.  It's based on what Sublime returns for line height.

Windows had some issues which required me to add additional workaround settings to tweak things.

Font size is tricky.  I think mdpopups CSS is handling that. I think it sets it to 1rem which should be the same size as the editor text, but that may not be exactly the case as Sublime doesn't quite get that right. I'll check that tomorrow when I have some time to give you a more exact answer.

**Comment by facelessuser** [comment] 2017-05-08 05:37
I've recently realized that people mistake the fact that I've purposely made certain text smaller in in ColorHelper (mainly UI links like the top menu etc.) that they think that ColorHelper font is too small.   Some of the UI text was made smaller to get it out of the way while the data (color info) is larger.  It was my attempt to de-emphasize the UI controls to focus on the data. In the next version I will make them a little bigger and hopefully people will find that a little better.

**Comment by GameKyuubi** [comment] 2017-05-08 06:06
Isn't this more about the size of the cells in the color picker?  I mean yes it would be nice if the text was more readable my main issue is that the picker cells themselves are too small to click on reasonably or even see the colors they hold.

**Comment by facelessuser** [comment] 2017-05-08 06:16
Ah, yeah, I forgot that was what this one was about, and closed this too hastily.

So yeah, originally small, medium, and large graphics sizes where based on non-4k.  I need to think about how I wish to approach this moving forward. Integer option is possible, or I could double everything for 4K screens.

Whatever I end up doing, it probably won't make it in the next release, but hopefully next after.

**Comment by GameKyuubi** [comment] 2017-05-08 06:25
Here's the current state of things for reference:

```
{
  "graphic_size": "large",
  "inline_preview_offset": -3,
}
```

![sublimecolorsmall](https://cloud.githubusercontent.com/assets/6174313/25792606/7719370a-3402-11e7-872e-3f781d95b481.png)

**Comment by facelessuser** [comment] 2017-05-08 06:48
One other thing I haven't asked you, what color scheme are you using?  I am wondering if it is also injecting some CSS because your previews look weird line spacing in popup is weird, there are just a lot of things weird.  I didn't think to ask this earlier, but color schemes can inject CSS that can really mess with things.

**Comment by GameKyuubi** [comment] 2017-05-08 06:51
The last screen cap is the default Monokai, the previous ones were the preinstalled Solarized Dark scheme.

**Comment by facelessuser** [comment] 2017-05-08 07:01
Yeah, default Monokai injects nothing.

I'm going to need to install your font when I get around to this. Your preview looks so bad it's comical, but I can't reproduce it with other fonts.  Sublime's minihtml sometimes distorts images depending on the line height, but yours looks really bad in that last screencap.  I don't even understand why the lines are so spread out at the bottom of the popup.

Anyways, this is on my list.  I'll do my best to reproduce.  At the very least, I will probably give more control over image size.

**Comment by WebVeteran** [comment] 2017-08-27 23:28
"Me too". Maybe you can give us a "2X Large" setting for size? Or give us an integer for % of the original "medium". For example we would enter "150" for something half as much bigger than medium.

sublime settings:
```
{
	"auto_complete_cycle": true,
	"auto_find_in_selection": true,
	"caret_extra_width": 1,
	"close_windows_when_empty": true,
	"color_scheme": "Packages/Agila Theme/Markdown/Oceanic Next Origin Markdown.tmTheme",
	"fade_fold_buttons": false,
	"font_face": "Menlo",
	"font_size": 10,
	"highlight_line": true,
	"ignored_packages":
	[
		"Vintage"
	],
	"margin": 2,
	"predawn_findreplace_small": true,
	"predawn_sidebar_xsmall": true,
	"predawn_tabs_small": true,
	"show_encoding": true,
	"show_line_endings": true,
	"tab_size": 2,
	"theme": "predawn.sublime-theme",
	"trim_trailing_white_space_on_save": true
}
```

ColorHelper settings:
```
{
	"use_webcolor_names": false,
	"inline_preview_position": "right",
	"graphic_size": "large",
	"use_hex_color_picker": false,
	"click_color_box_to_pick": "color_picker",
}
```

Output:
![screen shot 2017-08-27 at 7 24 25 pm](https://user-images.githubusercontent.com/40175/29754928-5bfd1196-8b5d-11e7-8a98-ad6ff06e25a2.png)

**Comment by facelessuser** [comment] 2017-08-28 01:02
I need to think about this. I'd like to come up with a scalable solution. Maybe short term x large would be fine. I'll have to look into it when I have some time.

**Comment by facelessuser** [comment] 2017-10-24 02:39
Okay.  I actually took a look at this.  This issue is due to the fact that the color boxes scale with the font size.  I'll have to look into creating some fixed sizes, or separate graphic sizes from font size with its own scaling.

**Comment by facelessuser** [comment] 2019-08-23 04:02
Moving forward, we should have better scaling.

- Coarse scaling with `graphic_size` will be better.
- Added new option `graphic_scale` which will allow fine scaling via a decimal value.
- Borders are removed in a lot of places or minimized to make viewing colors easier. 

Hopefully with all of these things, this will no longer be an issue moving forward.

**Closed** 2019-08-23 13:44 UTC
