### ISSUE TITLE
CSS Indentions

### ISSUE THREAD

**Issue by FileEX** [facelessuser/ColorHelper#239] opened 2022-12-01 17:44 UTC
## Description

**BUG**

Hello, I’m having a frustrating problem with CSS indentation.

When I type some class and press “Enter”, there is an indent before the class declaration. This only occurs if in class above is color preview.

![image](https://user-images.githubusercontent.com/26044224/205123035-334f8cae-5212-48c0-8f7a-eeb0d5afe31f.png)
Press enter...
![image](https://user-images.githubusercontent.com/26044224/205123092-974a2ffe-c16d-439a-8518-b47bf886fad6.png)

Without color preview indentations doesn't appear.
![image](https://user-images.githubusercontent.com/26044224/205123156-87ea2200-d2c9-4d44-a3ff-daf28762f71f.png)

I have no other packages.

Console is clear.

## Support Info
- ST ver.: 4143
- Platform: windows
- Arch: x64
- Plugin ver.: 6.0.3
- Install via PC: True
- mdpopups ver.: 4.2.2

## Steps to Reproduce Issue

1. Write some class in CSS with e.g "background-color" property.
2. Under class with color preview write second another class and press "enter"

**Comment by facelessuser** [comment] 2022-12-01 17:54
I am not experiencing this in any way. 

I am using the default CSS syntax (I'm not sure if you are or not). I'm using the latest Sublime Text as well:

![ch](https://user-images.githubusercontent.com/1055125/205124777-cd871f35-d04a-4eed-b6d8-20014aac0a99.gif)

The truth is, this could be caused by using some other syntax package that has some other snippets, maybe some other plugin, I have no idea, but I cannot seem to reproduce this, and it doesn't make sense that I would be able to. ColorHelper doesn't change the actual syntax of the code, it just injects an inline phantom.

If you have a reproducible example, please paste in plain text so I can copy/paste and test. Please provide any additional information you can think of that would help narrow this down the issue, language syntax package if you aren't using default CSS, if you are using some CSS LSP stuff, or other CSS related plugins, etc.

**Comment by facelessuser** [comment] 2022-12-02 14:51
Then this may be an issue with Sublime. All we are doing is inserting a phantom. This shouldn't change how Sublime processes text. In fact, it should **not** change how Sublime processes text.

Unfortunately, my hands are probably tied on this as I have no way to fix what Sublime is doing. A possible workaround is to set `preview_on_select` to `true` in the settings. This would only render previews on a line when you select the line. This may alleviate the weird indentation issue as phantoms would not be rendered by default except on a line you are selecting. As soon as a line is no longer focused, previews should go away.

Sublime should fix this issue, I don't believe plugins are responsible.

**Comment by facelessuser** [comment] 2022-12-02 15:31
As this seems to be an upstream issue, we will close the issue here.

**Closed by facelessuser** 2022-12-02 15:31 UTC
Labels: S: more-info-needed, S: triage
