### ISSUE TITLE
[Feature request] Support X11 color names in color scheme files

### ISSUE THREAD

**Issue by Kristinita** [facelessuser/ColorHelper#80] opened 2017-01-01 08:54 UTC
### 1. Request

It would be nice, if you add support [**X11 color names**](https://en.wikipedia.org/wiki/Web_colors#X11_color_names) for `.tmTheme` files. See [**comment**](https://github.com/facelessuser/ColorHelper/issues/70#issuecomment-263311468).

### 2. Justification

Now HEX colors in `.tmTheme` files are highlighted, but X11 colors not highlighted.

![HEX and X11](https://camo.githubusercontent.com/8e2ae827c8698cc496f8c9198c2ab7eadf8f9150/687474703a2f2f692e696d6775722e636f6d2f6164364f6365462e706e67)

### 3. Desirable behavior

Color square near X11 color names in `.tmTheme` files like HEX color names.

### 4. Environment

- ST ver.: 3126
- Platform: windows
- Arch: x32
- Plugin ver.: 2.4.0
- Install via PC: True
- mdpopups ver.: 1.13.1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

Thanks.

**Comment by facelessuser** [comment] 2017-01-01 15:37
This is a duplicate of issue #42.

This currently needs a big refactoring of the code to handle proper as this was originally designed for CSS colors.  People are actually interested in doing various non-CSS color formats, and this will require a large refactoring to accomplish (or at least to accomplish by making my life easier for similar requests in the future.

This request in particular brings up another potential problem as tmTheme allow for CSS embedded in popupCSS and phantomCSS.  The embedded CSS allows for CSS color names, while the tmTheme only allows X11 color names.  There would be a collision in scanning.  I'm not currently sure how or if I will bother handling such a case.  Anyways, I will close this issue for now as #42 covers the support needed to get this in.

**Closed by facelessuser** 2017-01-01 15:37 UTC
Labels: Duplicate
