### ISSUE TITLE
`--red` makes the color phantom "blink"

### ISSUE THREAD

**Issue by math2001** [facelessuser/ColorHelper#89] opened 2017-03-13 08:55 UTC
## Description

An image is worth much more in this case:

![temp gif](https://cloud.githubusercontent.com/assets/15224242/23846923/045c81b8-0824-11e7-9081-39a55cfba928.gif)

As you can, it gives this "blinking" effect, which keeps catching my eyes, and... well, it's harder to focus.

*it removes the phantom and re-adds it with a delay, that's all*

> For bugs and support questions:

After a few tries, it seems that it's the *prefix* `--red` that creates this. Didn't find any other yet. The color doesn't change anything (you can change it, it keeps blinking)

Didn't find any error in the console

## Plugins

Because you've done such an awesome job, I reverted to a fresh state and installed PC and color helper *only*, and tried: it still blinks.

## Support Info

- ST ver.: 3126
- Platform: windows
- Arch: x64
- Plugin ver.: 2.4.2
- Install via PC: True
- mdpopups ver.: 1.13.1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

*Note: how about using a popup for instead of the popup, like on the [Boxy](https://github.com/ihodev/sublime-boxy/pull/151)*

## Steps to Reproduce Issue

Type in `--red: ` 😄 and a color. Copy/paste:

```css
html {
   --red: #f00;
   --blue: #0f0
}
```

**Comment by stoivo** [comment] 2017-03-13 11:11
Duplicate of https://github.com/facelessuser/ColorHelper/issues/88, I think it can be closed.

**Closed** 2017-03-13 13:10 UTC
Labels: Duplicate
