### ISSUE TITLE
Request: Support "bare" RBG tuples (without "RGB(" and ")"

### ISSUE THREAD

**Issue by AndydeCleyre** [facelessuser/ColorHelper#123] opened 2019-08-18 18:26 UTC
## Description

KDE Plasma and applications use an RGB configuration format for colors like in the following exceprts:

```ini
[Background]
Color=38,44,46

[BackgroundFaint]
Color=38,44,46

[BackgroundIntense]
Color=38,44,46
```

```ini
[Colors:Button]
BackgroundAlternate=64,69,82
BackgroundNormal=34,34,34
DecorationFocus=169,77,55
DecorationHover=169,77,55
ForegroundActive=222,160,80
ForegroundInactive=103,103,103
ForegroundLink=222,160,80
ForegroundNegative=230,73,118
ForegroundNeutral=168,123,96
ForegroundNormal=194,183,144
ForegroundPositive=112,157,61
ForegroundVisited=186,185,114
```

But these RGB tuples are not recognized as such by this plugin yet.

This is a request to add recognition for this "bare RGB" pattern. At least in the case of KDE configs, any of these PCREs would match very well:

`\S+=(\d{1,3},\d{1,3},\d{1,3})$`
`^\S+=(\d{1,3},\d{1,3},\d{1,3})$`
`\S+=(\d+,\d+,\d+)$`
`^\S+=(\d+,\d+,\d+)$`

Those should all work with Python's `re` as well.

**Comment by facelessuser** [comment] 2019-08-18 21:35
There is a plan to abstract the color stuff in such a way to make it easier for users to add custom colors, but that work has not been done yet. Currently, ColorHelper just supports HTML/CSS color formats. It is possible that in the future your desire will be possible. In the way the code is currently written, I have no desires to add additional custom formats.

**Comment by facelessuser** [comment] 2019-11-21 13:45
@gir-bot add T: feature, S: maybe

**Comment by facelessuser** [comment] 2019-11-21 13:46
@gir-bot add P: maybe

**Comment by facelessuser** [comment] 2019-11-21 14:02
Closing as duplicate of #141 

@gir-bot add S: duplicate

**Closed by facelessuser** 2019-11-21 14:02 UTC
Labels: P: maybe, T: feature
