### ISSUE TITLE
Support for CSS variables

### ISSUE THREAD

**Issue by oalberdi** [facelessuser/ColorHelper#69] opened 2016-11-21 13:56 UTC
Hi, 
would be great also to have support for the new css variables, often used for color.
They are set using custom property notation (e.g. --main-color: black;) and are accessed using the var() function (e.g. color: var(--main-color);)

Both, displaying the color next to the var, or function on right menu "go to definition" would be awesome.

Thanks!

## Support Info

- ST ver.: 3125
- Platform: windows
- Arch: x64
- Plugin ver.: 2.2.0
- Install via PC: True
- mdpopups ver.: 1.12.1
- markdown ver.: 2.6.6
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

**Comment by facelessuser** [comment] 2016-11-23 19:22
@oalberdi Thanks for your interest in this plugin.  Recently I added a template for new issues (I am still iterating through to make more clear in it what I am looking for in the issues) and I currently require people to use the template in order to get an official response.  Your description is fine, but you could you also add the support info that the template asks for?  https://github.com/facelessuser/ColorHelper/blob/master/.github/ISSUE_TEMPLATE.md#support-info.

I'm trying to get everyone in the habit of following the template so I don't have to ask people for common stuff.  And I can be sure that they aren't missing a feature because they are on old versions etc.  While this is clearly not the case with your request, I have to be consistent with everyone.

Thanks.

**Comment by oalberdi** [comment] 2016-11-29 09:35
Hi,
Ok. I understand. Sorry for not following the template. 
Thanks for the reply.

**Comment by facelessuser** [comment] 2016-11-29 17:03
I went ahead and updated the opening post with the most recent version I am using.  Each issue is an example to others, so I do this for consistency.  Even when I create an issue, I put in my current versions to encourage the same from others.

As for your request.  Currently there are no plans for this.  I have a big refactoring to take place soon to make the plugin more flexible.  People want to use this outside of just CSS/html.  This is going to take me a bit to do.  As for Sass/CSS/SCSS variables, I am undecided on this at the present.  This would be very stylesheet specific, but I am not against it.  But I'll have to see if/how it would fit into the current code.  I'm actually not a web developer, so when I created this, things such as this were not considered.  

I will have to think about this.

**Comment by jrappen** [comment] 2017-10-23 23:07
@facelessuser Don't want to go too far off-topic...Just a quick FYI.

When requiring people to fill out the issue template, you could also prefill the issue body directly from Sublime by opening a new browser tab. Format below:

```text
https://github.com/facelessuser/ColorHelper/issues/new/?
    labels=discussion,watchlist&
    assignee=facelessuser&
    title=Some%20title&
    body=Some%20body
```

* Haven't tested applying `Projects` or `Milestones`, but I assume that's similar.
* Applying those two, assignees and labels will naturally only work for repo maintainers who click the link.
* Title and body though works for anybody.

**Comment by facelessuser** [comment] 2017-10-23 23:14
This is interesting.  I guess you could open up a Issue view where you specify title and body (some of it prefilled).  And then run a command to create the issue.  That could work.  I'd have to play with it and ensure I could format it correctly, but thanks for the tip.

**Comment by kaiserkiwi** [comment] 2017-11-02 11:42
Recently started to use CSS variables in a new project. It’s a real pity that ColorHelper doesn’t supports this feature. I would be very grateful if you could consider this in a future release as CSS variables become more common.

**Comment by facelessuser** [comment] 2017-11-02 19:58
@kaiserkiwi, I support a bunch of different plugins for Sublime Text, and even some repos outside of that.  This is extremely low priority for me currently (assuming I decide to follow through with this).

**Comment by facelessuser** [comment] 2019-11-21 14:00
@gir-bot add S: duplicate

Closing as a duplicate of #142

**Closed** 2019-11-21 14:00 UTC
Labels: P: maybe, S: duplicate, T: feature
