### ISSUE TITLE
Support for SCSS (SASS) Variables Coloring

### ISSUE THREAD

**Issue by bgarrant** [facelessuser/ColorHelper#101] opened 2017-12-10 12:18 UTC
Is there any chance of Color Helper supporting SCSS (SASS) variable coloring throughout the files?  The main variable declaration is colored, by when the variable is used again it is not colored.  Gutter Color used to be able to do this so there must be a way.  Any help is appreciated.

![screen shot 2017-12-10 at 7 15 47 am](https://user-images.githubusercontent.com/2436728/33804757-0ac10bf6-dd7a-11e7-8857-4e88c8234ad3.png)

**Comment by facelessuser** [comment] 2017-12-10 18:20
I don't know what Gutter Color is, but to do this, you have to always parse the whole file to find such variable declarations, then you have to parse the colors.  I parse a sliding window for colors to avoid performance issues currently.

This is essentially a duplicate of #69, but for SAS variables, but if I ever get around to this, these would be handled together.  I'm not sure if/when I would get around to this.

**Comment by facelessuser** [comment] 2019-11-21 14:01
Closing as a duplicate of #142 

@gir-bot add S: duplicate

**Closed by facelessuser** 2019-11-21 14:01 UTC
Labels: P: maybe, T: feature
