### ISSUE TITLE
Project palette doesn't show up in palette tooltip

### ISSUE THREAD

**Issue by duggum** [facelessuser/ColorHelper#111] opened 2018-04-19 01:46 UTC
## Description

> - Describe the bug/question in as much detail as possible to make it clear what is wrong or what you do not > understand.

**Project colour palettes do not show up in the palette tooltip. I have tried quitting Sublime Text after creating a palette, as well as reinstalling the plugin.**

> - Provide errors from console (if available).

**None; even with debug mode enabled.**

> - Pictures or screencasts can also be used to clarify what the issue is or what the question is.

![project-palette](https://user-images.githubusercontent.com/6613807/38966349-c8165518-434f-11e8-9690-02c59713180f.png)
**In the above image you can see the palette created in my project file (left), but it does not show up in the palette tooltip (right).**

> - Provide links to 3rd party syntax highlighting package you are using if applicable.

## Support Info

> Run the following command from the menu: `Preferences->Package Settings->ColorHelper->Support Info`.  Post the result here.

- ST ver.: 3164
- Platform: osx
- Arch: x64
- Plugin ver.: 2.5.1
- Install via PC: True
- mdpopups ver.: 3.3.2
- markdown ver.: 2.6.11
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

## Steps to Reproduce Issue

> Provide steps to reproduce the issue. Pictures are fine, but also provide code/text I can copy and paste in order to reproduce. Omit for feature requests and feature proposals.

**1. Click on a colour in an open file and select 'add' from the tooltip.
2. Select 'Create New Project Palette' from the add tooltip
3. Type in palette name and press enter.
4. Confirm palette has been added to 'color_helper_palettes' section of current sublime-project file.
5. Click on a colour in an open file and select 'palettes' from the tooltip.
6. The newly created palette should be listed, but it is not.**

**Comment by facelessuser** [comment] 2018-04-19 02:41
Thanks for the report. Please post text examples for copy and paste in addition to the pictures.  If I'm able to copy and paste, I am more likely to attempt to reproduce and address the issue.

**Comment by duggum** [comment] 2018-04-19 02:45
> Thanks for the report. Please post text examples for copy and paste in addition to the pictures. If I'm able to copy and paste, I am more likely to attempt to reproduce and address the issue.

Sorry, but I'm not sure what you mean here. Do you want my CSS and sublime-project file text?

I tried this with multiple projects and different files containing colour codes, so it isn't unique to a single project or source file.

**Comment by facelessuser** [comment] 2018-04-19 03:07
Just your example color palette would be nice.

**Comment by duggum** [comment] 2018-04-20 01:41
The attached is the JSON code from my sublime-project file and the random CSS code I used for testing. Because the palette doesn't show up in the tooltip, I could not add more than one colour, so the other two you see in the JSON were added manually just to see if it would show up with more than one colour in the palette, but it didn't make a difference. 

``` json
"color_helper_palettes":
[
  {
    "colors":
    [
      "#ff0000",
      "#ffff00",
      "#0000ff",
    ],
    "name": "DJ"
  }
],
```

``` css
a {
  color: red
}

a c,
a d,
a span {
  color: #fff
}

span a {
  color: #00f
}

@media (min-width:30em) {
  a {
    color: #ff0
  }
}
```

**Comment by SDemonUA** [comment] 2018-05-21 12:50
I have same issue

**Comment by facelessuser** [comment] 2018-05-21 16:19
I've been busy, when I get a chance, I'll take a look.

**Comment by SDemonUA** [comment] 2018-05-28 23:09
Hey, there
I believe I know what is wrong:
https://github.com/facelessuser/ColorHelper/blob/02e07bce00ee24181530c28e3d22d3ee1e2b1c1c/color_helper.py#L732

**Comment by facelessuser** [comment] 2019-08-22 02:10
Finally got around to seeing what the issue is. Better late than never. Anyways @SDemonUA was on the right track, but the issue was that we were overwriting our project palettes with a new variable. This will be fixed in the next version.

**Closed** 2019-08-22 02:39 UTC
